import {
  Atom,
  FlaskConical,
  Sigma,
  Dna,
  BookOpen,
  Code2,
  Globe2,
  MessageCircle,
  Mic,
  Users,
  Sparkles,
  Brain,
  Lightbulb,
  Compass,
  HeartHandshake,
  MonitorSmartphone,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  atom: Atom,
  "flask-conical": FlaskConical,
  sigma: Sigma,
  dna: Dna,
  "book-open": BookOpen,
  "code-2": Code2,
  "globe-2": Globe2,
  "message-circle": MessageCircle,
  mic: Mic,
  users: Users,
  sparkles: Sparkles,
  brain: Brain,
  lightbulb: Lightbulb,
  compass: Compass,
  "heart-handshake": HeartHandshake,
  "monitor-smartphone": MonitorSmartphone,
};
